package com.example.support.performance;

import com.example.support.classifier.Classifier;
import com.example.support.dto.BulkImportSummary;
import com.example.support.dto.CreateTicketRequest;
import com.example.support.dto.TicketDto;
import com.example.support.dto.TicketFilter;
import com.example.support.repository.TicketRepository;
import com.example.support.service.TicketService;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.mock.web.MockMultipartFile;

import java.nio.charset.StandardCharsets;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Micro-benchmarks that exercise the service layer directly (bypassing HTTP)
 * against the real H2-backed {@link TicketRepository}. Thresholds are set
 * generously above what any of these operations should realistically take on
 * developer/CI hardware, so these tests catch severe regressions (e.g. an
 * accidental N+1 query or an O(n^2) loop) without being flaky under load.
 *
 * <p>Results are logged so they can be copied into the performance
 * benchmarks table in TESTING_GUIDE.md.
 */
@SpringBootTest
class PerformanceBenchmarkTest {

    private static final Logger log = LoggerFactory.getLogger(PerformanceBenchmarkTest.class);

    @Autowired
    private TicketService ticketService;

    @Autowired
    private TicketRepository ticketRepository;

    @Autowired
    private Classifier classifier;

    @BeforeEach
    void setUp() {
        ticketRepository.deleteAll();
    }

    @AfterEach
    void tearDown() {
        ticketRepository.deleteAll();
    }

    private CreateTicketRequest request(int i) {
        CreateTicketRequest req = new CreateTicketRequest();
        req.setCustomerEmail("perf" + i + "@example.com");
        req.setCustomerName("Perf User " + i);
        req.setSubject("Performance test ticket " + i);
        req.setDescription("This ticket is generated by a performance benchmark test iteration " + i);
        return req;
    }

    // =========================================================================
    // 1. Ticket creation throughput
    // =========================================================================

    @Test
    void ticketCreation_averageLatencyUnderThreshold() {
        int iterations = 200;

        long start = System.nanoTime();
        for (int i = 0; i < iterations; i++) {
            ticketService.createTicket(request(i), false);
        }
        long elapsedMs = (System.nanoTime() - start) / 1_000_000;
        double avgMs = (double) elapsedMs / iterations;

        log.info("[perf] createTicket: {} ops in {} ms (avg {} ms/op)", iterations, elapsedMs, avgMs);
        assertThat(avgMs).isLessThan(100.0);
    }

    // =========================================================================
    // 2. Bulk import throughput
    // =========================================================================

    @Test
    void bulkImport_ofTwoHundredRecords_completesUnderThreshold() {
        StringBuilder csv = new StringBuilder("customer_email,customer_name,subject,description\n");
        for (int i = 0; i < 200; i++) {
            csv.append("bulk").append(i).append("@example.com,Bulk User ").append(i)
                    .append(",Bulk subject ").append(i)
                    .append(",This is a bulk-imported performance test description number ").append(i)
                    .append("\n");
        }
        MockMultipartFile file = new MockMultipartFile(
                "file", "bulk.csv", "text/csv", csv.toString().getBytes(StandardCharsets.UTF_8));

        long start = System.nanoTime();
        BulkImportSummary summary = ticketService.importTickets(file, false);
        long elapsedMs = (System.nanoTime() - start) / 1_000_000;

        log.info("[perf] bulkImport: {} records in {} ms", summary.getTotalRecords(), elapsedMs);
        assertThat(summary.getSuccessful()).isEqualTo(200);
        assertThat(elapsedMs).isLessThan(10_000);
    }

    // =========================================================================
    // 3. GET /tickets listing performance against a larger dataset
    // =========================================================================

    @Test
    void listTickets_withFiveHundredRecords_completesUnderThreshold() {
        for (int i = 0; i < 500; i++) {
            ticketService.createTicket(request(i), false);
        }

        long start = System.nanoTime();
        List<TicketDto> tickets = ticketService.getTickets(new TicketFilter());
        long elapsedMs = (System.nanoTime() - start) / 1_000_000;

        log.info("[perf] listTickets: {} records fetched in {} ms", tickets.size(), elapsedMs);
        assertThat(tickets).hasSize(500);
        assertThat(elapsedMs).isLessThan(5_000);
    }

    // =========================================================================
    // 4. Classification throughput (pure in-memory, no DB access)
    // =========================================================================

    @Test
    void classification_averageLatencyUnderThreshold() {
        int iterations = 2_000;

        long start = System.nanoTime();
        for (int i = 0; i < iterations; i++) {
            classifier.classify("Critical production down", "This is a critical production down incident #" + i);
        }
        long elapsedMs = (System.nanoTime() - start) / 1_000_000;
        double avgMicros = (elapsedMs * 1000.0) / iterations;

        log.info("[perf] classify: {} ops in {} ms (avg {} us/op)", iterations, elapsedMs, avgMicros);
        assertThat(elapsedMs).isLessThan(2_000);
    }

    // =========================================================================
    // 5. Concurrent read throughput
    // =========================================================================

    @Test
    void concurrentReads_twentyFiveThreads_completeUnderThreshold() throws Exception {
        for (int i = 0; i < 100; i++) {
            ticketService.createTicket(request(i), false);
        }

        int threadCount = 25;
        ExecutorService executor = Executors.newFixedThreadPool(threadCount);
        try {
            long start = System.nanoTime();
            List<Future<Integer>> futures = IntStream.range(0, threadCount)
                    .<java.util.concurrent.Callable<Integer>>mapToObj(i -> () -> ticketService.getTickets(new TicketFilter()).size())
                    .map(executor::submit)
                    .collect(Collectors.toList());

            List<Integer> sizes = new java.util.ArrayList<>();
            for (Future<Integer> f : futures) {
                sizes.add(f.get(30, TimeUnit.SECONDS));
            }
            long elapsedMs = (System.nanoTime() - start) / 1_000_000;

            log.info("[perf] concurrentReads: {} threads in {} ms", threadCount, elapsedMs);
            assertThat(sizes).hasSize(threadCount);
            assertThat(sizes).allMatch(size -> size == 100);
            assertThat(elapsedMs).isLessThan(10_000);
        } finally {
            executor.shutdown();
        }
    }
}
