"""Generated by the Unit Test Generator agent for the changes recorded in
context/bugs/001/fix-summary.md. Scope: src/taskflow/store.py (search,
sorted_by_priority) and src/taskflow/cli.py (export_tasks) only — the files
the Bug Fixer changed for bug 001. See skills/unit-tests-FIRST.md.
"""

import os
import tempfile
import unittest

import context  # noqa: F401  (adds src/ to sys.path)

from taskflow.store import TaskStore
from taskflow.cli import export_tasks
import taskflow.cli as cli


class SearchOffByOneFixTests(unittest.TestCase):
    """Covers fix-summary.md Change 1: src/taskflow/store.py TaskStore.search."""

    def setUp(self):
        # Independent: fresh store per test, no shared state across tests.
        self.store = TaskStore()

    def test_search_matches_title_starting_with_term(self):
        # Before the fix, find(...) > 0 excluded a match at index 0.
        self.store.add("Milk run", priority=1)
        results = self.store.search("Milk")
        self.assertEqual([t.title for t in results], ["Milk run"])

    def test_search_is_case_insensitive_at_start(self):
        self.store.add("milk run", priority=1)
        results = self.store.search("MILK")
        self.assertEqual(len(results), 1)

    def test_search_still_matches_mid_string_term(self):
        # Regression guard: the fix must not break the previously-working case.
        self.store.add("Buy milk", priority=1)
        results = self.store.search("milk")
        self.assertEqual(len(results), 1)

    def test_search_no_match_returns_empty_list(self):
        self.store.add("Milk run", priority=1)
        self.assertEqual(self.store.search("bread"), [])


class PrioritySortFixTests(unittest.TestCase):
    """Covers fix-summary.md Change 2: src/taskflow/store.py TaskStore.sorted_by_priority."""

    def setUp(self):
        self.store = TaskStore()

    def test_double_digit_priority_outranks_single_digit(self):
        # Before the fix, str-based sort placed priority 2 ahead of priority 10.
        self.store.add("Low prio", priority=2)
        self.store.add("High prio", priority=10)
        ordered = self.store.sorted_by_priority()
        self.assertEqual([t.priority for t in ordered], [10, 2])

    def test_sorted_by_priority_is_fully_descending(self):
        for priority in (3, 11, 1, 20, 2):
            self.store.add(f"task-{priority}", priority=priority)
        ordered = [t.priority for t in self.store.sorted_by_priority()]
        self.assertEqual(ordered, sorted(ordered, reverse=True))


class ExportCommandInjectionFixTests(unittest.TestCase):
    """Covers fix-summary.md Change 3: src/taskflow/cli.py export_tasks."""

    def setUp(self):
        # Independent: reset the module-level store used by export_tasks.
        cli._store = TaskStore()

    def test_export_grep_filters_by_plain_substring(self):
        cli._store.add("Buy milk", priority=1)
        cli._store.add("Write report", priority=1)
        with tempfile.TemporaryDirectory() as tmp:
            out_path = os.path.join(tmp, "out.txt")
            export_tasks(out_path, grep_term="milk")
            with open(out_path, encoding="utf-8") as f:
                content = f.read()
        self.assertIn("Buy milk", content)
        self.assertNotIn("Write report", content)

    def test_export_grep_term_is_not_shell_interpreted(self):
        # Regression test for the fixed CWE-78 command injection: a payload that
        # used to spawn `echo` via a shell must now be treated as an inert,
        # non-matching literal substring.
        cli._store.add("Buy milk", priority=1)
        payload = "milk & echo pwned> PWNED_by_injection.txt & rem"
        with tempfile.TemporaryDirectory() as tmp:
            out_path = os.path.join(tmp, "out.txt")
            export_tasks(out_path, grep_term=payload)
            pwned_path = os.path.join(tmp, "PWNED_by_injection.txt")
            self.assertFalse(os.path.exists(pwned_path))
            self.assertFalse(os.path.exists("PWNED_by_injection.txt"))

    def test_export_without_grep_writes_all_titles(self):
        cli._store.add("Buy milk", priority=1)
        cli._store.add("Write report", priority=1)
        with tempfile.TemporaryDirectory() as tmp:
            out_path = os.path.join(tmp, "out.txt")
            export_tasks(out_path)
            with open(out_path, encoding="utf-8") as f:
                content = f.read()
        self.assertIn("Buy milk", content)
        self.assertIn("Write report", content)


if __name__ == "__main__":
    unittest.main()
